# Generated by Django 6.0.1 on 2026-02-02 01:50

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('cpu', models.CharField(max_length=200, verbose_name='Процессор')),
                ('gpu', models.CharField(max_length=200, verbose_name='Видеокарта')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('storage', models.CharField(max_length=200, verbose_name='Накопитель')),
                ('motherboard', models.CharField(max_length=200, verbose_name='Материнская плата')),
                ('psu', models.CharField(max_length=100, verbose_name='Блок питания')),
                ('case', models.CharField(blank=True, max_length=200, verbose_name='Корпус')),
                ('cooling', models.CharField(blank=True, max_length=200, verbose_name='Охлаждение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('warranty_months', models.IntegerField(default=36, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Гарантия (месяцы)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фото ПК')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Конфигурация ПК',
                'verbose_name_plural': 'Конфигурации ПК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('msi', 'MSI Gaming'), ('steam', 'Steam Library'), ('apple', 'Apple Premium'), ('spotify', 'Spotify Minimal'), ('mixpc', 'MIXPC Series')], default='msi', max_length=20, verbose_name='Стиль')),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated/', verbose_name='Изображение')),
                ('card_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Номер в серии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cards', to='cards.pcbuild', verbose_name='Конфигурация')),
            ],
            options={
                'verbose_name': 'Сгенерированная карточка',
                'verbose_name_plural': 'Сгенерированные карточки',
                'ordering': ['-created_at', 'card_number'],
            },
        ),
    ]
